<a href="https://colab.research.google.com/github/rosywaruku/ML-Tasks/blob/main/Feature%20Selection/feature_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD,PCA
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
svd= TruncatedSVD(3)
pca= PCA(3)

In [ ]:
size=100,5

In [ ]:
values=np.random.uniform(10,100,size)

In [ ]:
data={'Loc':[],'Size':[],'Mall_near':[], 'Ambience':[],'Monthly_rent':[]}

In [ ]:
df=pd.DataFrame(values, columns = data)
df

          Loc       Size  Mall_near   Ambience  Monthly_rent
0   56.026532  33.474972  11.317541  91.077590     67.245593
1   80.654747  86.153533  19.677264  43.945978     46.127865
2   55.288528  21.931284  74.793231  86.913316     34.035555
3   80.922174  55.177411  96.348030  78.254661     23.318076
4   67.345728  73.363923  53.656330  70.626615     69.794468
..        ...        ...        ...        ...           ...
95  87.435146  99.933159  78.287634  10.069458     69.654959
96  68.914578  27.325922  19.500948  74.300561     72.805889
97  14.619045  78.343125  50.678700  97.992581     82.456848
98  41.991887  99.471458  39.474703  37.563445     85.545775
99  60.672134  50.171659  49.624453  36.372062     91.552942

[100 rows x 5 columns]

In [ ]:
#specify the target
nominal=['Loc','Mall_near']
ordinal=['Ambience']
numerical = ['Size']
features=['Loc','Size','Mall_near','Ambience']
target = ['Monthly_rent']

for feature in ordinal:
  value = df[feature]
  encoder = LabelEncoder()
  trans_f = encoder.fit_transform(value)
  df[feature]=trans_f

df

          Loc       Size  Mall_near  Ambience  Monthly_rent
0   56.026532  33.474972  11.317541        89     67.245593
1   80.654747  86.153533  19.677264        38     46.127865
2   55.288528  21.931284  74.793231        84     34.035555
3   80.922174  55.177411  96.348030        73     23.318076
4   67.345728  73.363923  53.656330        62     69.794468
..        ...        ...        ...       ...           ...
95  87.435146  99.933159  78.287634         0     69.654959
96  68.914578  27.325922  19.500948        64     72.805889
97  14.619045  78.343125  50.678700        98     82.456848
98  41.991887  99.471458  39.474703        31     85.545775
99  60.672134  50.171659  49.624453        29     91.552942

[100 rows x 5 columns]

### Divide the data into the features and the target

In [ ]:
# get target and predictive features 
y =df[target]
X = df[features]
y.head()

   Monthly_rent
0     67.245593
1     46.127865
2     34.035555
3     23.318076
4     69.794468

###Check for nulls in the target feature

In [ ]:
y.isnull().values.any()

False

### Check for nulls in predictive features

In [ ]:
X.isnull().values.any()

False

In [ ]:
svd.fit_transform(X,y)

array([[ 9.36821855e+01,  5.05575876e+00, -5.75380251e+01],
       [ 1.14092441e+02, -5.05316656e+01, -7.13246937e+00],
       [ 1.16089015e+02,  4.32297145e+01, -2.27978303e+01],
       [ 1.52102875e+02,  2.20389222e+01,  9.44803949e-01],
       [ 1.28487212e+02, -7.66878388e+00, -4.40812547e+00],
       [ 1.34894893e+02, -3.15665981e+01,  7.83024836e+00],
       [ 8.28896471e+01,  1.41875089e+01, -2.09433955e-01],
       [ 1.19632864e+02,  7.32775450e+01, -1.47558395e+01],
       [ 1.21278246e+02,  3.70654966e+01, -1.54515737e+01],
       [ 1.05052711e+02,  5.78626885e+01, -8.35245081e+00],
       [ 5.91795412e+01, -3.94738775e+01,  1.93311805e+00],
       [ 1.44653429e+02,  1.52487934e+01, -9.11663050e-01],
       [ 7.84474499e+01,  3.95428063e+01,  5.33005675e+01],
       [ 1.00203366e+02,  2.36736428e+00,  2.62198409e+01],
       [ 1.67935916e+02,  9.35524730e+00,  1.51386411e+00],
       [ 1.34324493e+02, -1.54088062e+01,  1.38811879e+01],
       [ 1.01062337e+02,  2.07353794e+01,  6.19827952e+01],
       [ 6.69380911e+01, -3.22639294e+00,  2.33423092e+01],
       [ 1.27631810e+02,  4.24682543e+01,  1.91738801e+01],
       [ 8.54098176e+01, -5.60259419e+00,  2.92441104e+01],
       [ 1.17295420e+02, -2.39756406e+01, -1.81384330e+01],
       [ 1.04671815e+02, -1.04990455e-01,  4.13394822e+01],
       [ 1.35985594e+02, -1.60282658e+01,  6.12993616e+00],
       [ 1.19889042e+02, -3.32540264e+01, -1.50860525e+01],
       [ 1.14597163e+02, -3.04434247e+00, -5.14493546e+01],
       [ 1.38888430e+02, -5.15039477e+01, -3.12857504e+01],
       [ 1.05858757e+02, -2.18858277e+00, -2.57050357e+01],
       [ 7.25142908e+01, -7.98673673e+00, -3.40023866e+01],
       [ 1.01730246e+02,  4.25489209e+01,  3.69278729e+01],
       [ 1.12550541e+02, -9.30922743e+00,  1.94963927e+01],
       [ 8.10677319e+01, -1.14973594e+01,  3.35140502e+01],
       [ 1.24141331e+02, -5.35441615e+01, -3.44811283e+00],
       [ 1.10422526e+02, -3.48809122e+01,  1.67285692e+01],
       [ 7.12365470e+01, -7.60109938e+00, -7.93456538e+00],
       [ 9.37178386e+01,  2.02918745e+01, -2.46280486e+01],
       [ 9.52123949e+01, -1.01687325e+01, -2.97553377e+01],
       [ 1.48684596e+02, -8.02653143e+00,  1.81784066e+01],
       [ 6.52749404e+01, -8.68845506e+00,  2.75502868e+01],
       [ 1.42236384e+02,  2.82045045e+01,  4.06595368e+00],
       [ 1.04959540e+02, -2.78503872e+01,  1.06247214e+01],
       [ 7.72419301e+01, -1.77285528e+01, -1.13482205e+01],
       [ 1.14908943e+02, -5.74411505e+01, -9.66677315e-01],
       [ 1.16283440e+02, -4.82450977e+01, -5.27622797e+00],
       [ 1.23101975e+02,  3.96154559e+01, -3.52038990e+01],
       [ 1.10627939e+02, -6.98176091e+01,  1.60818589e+01],
       [ 1.13485132e+02,  8.27027117e+00, -1.63114335e+00],
       [ 1.05443967e+02, -1.66288533e+01, -2.37298244e+01],
       [ 6.70221354e+01,  2.61544308e+01,  3.34363295e+01],
       [ 1.44499207e+02,  9.14595299e+00, -3.48929597e+01],
       [ 1.32940275e+02,  1.33317266e+01,  2.39841104e+01],
       [ 1.05320295e+02, -1.23477770e+00, -5.45076380e+01],
       [ 1.36217031e+02,  2.76134909e+01, -1.26789843e+01],
       [ 1.01165622e+02,  4.16178815e+01, -3.50405820e+01],
       [ 3.73548694e+01,  8.92892262e-01, -3.21796217e+00],
       [ 9.01156672e+01, -1.77224961e+00,  1.64501982e+01],
       [ 1.21639289e+02,  6.20680776e+01, -1.57685756e+01],
       [ 1.05535240e+02, -6.27657557e+01, -5.38527146e-02],
       [ 5.65889732e+01,  1.86308541e+01,  2.81951200e+01],
       [ 9.17171559e+01,  1.62848688e+01,  1.15573327e+01],
       [ 8.03433674e+01,  9.12191027e+00,  8.68232099e+00],
       [ 8.87802211e+01,  4.71892199e+01,  3.19854173e+01],
       [ 1.30283306e+02,  1.52097481e+01,  4.84042815e+01],
       [ 1.39465446e+02, -2.88729258e+01,  2.41801432e+01],
       [ 9.79160367e+01, -3.85932626e+01,  4.62321930e+00],
       [ 1.18477044e+02,  1.45971755e+01,  5.17315429e+01],
       [ 1.51239073e+02, -4.30454828e+01, -4.15239009e+01],
       [ 1.09473835e+02, -6.63483193e+00,  1.31233425e+01],
       [ 1.23951435e+02,  4.41477648e+00,  3.51053036e+00],
       [ 1.21432549e+02, -4.05266283e+01, -3.10558371e+00],
       [ 8.08254060e+01,  4.01883312e+01,  6.40826411e+00],
       [ 1.00458876e+02,  3.05466313e+00, -2.66161822e+01],
       [ 1.22246210e+02, -1.55298678e+01, -4.93319082e+01],
       [ 1.51371276e+02,  1.17461467e+01, -1.74225782e+01],
       [ 1.81222571e+02,  2.03937264e+01,  5.08118887e+00],
       [ 9.01979672e+01, -7.88087993e+00, -2.40116000e+01],
       [ 1.13124025e+02, -1.09943260e+01, -3.76159391e+01],
       [ 5.47574137e+01, -9.78492444e+00, -1.07263099e-01],
       [ 4.21986927e+01, -1.13477513e+01,  2.31541515e+00],
       [ 1.60489643e+02,  2.75748521e+01,  1.30995651e+01],
       [ 6.46033465e+01, -3.13156963e+01,  7.19890898e+00],
       [ 1.39362143e+02,  2.27629803e+00, -2.98243615e+01],
       [ 1.20387844e+02, -5.59024914e+00,  4.98524453e+01],
       [ 1.24470014e+02,  2.48829609e+01,  8.26396137e+00],
       [ 1.10487609e+02,  1.45682571e+01,  1.85550337e+00],
       [ 1.06813078e+02, -7.24025416e+00, -1.03537428e+01],
       [ 6.66673995e+01, -3.40569018e+01, -1.21599093e+00],
       [ 8.10976451e+01,  1.46624340e+01, -1.87166156e+01],
       [ 5.60988975e+01, -2.03065023e+01,  2.44264532e+01],
       [ 7.57005192e+01,  2.65226463e+01,  4.47229159e+01],
       [ 1.07627701e+02,  6.01992082e+01, -1.53043488e+01],
       [ 1.02894983e+02, -6.28744925e+00, -4.55950571e+01],
       [ 1.23369703e+02, -4.94929869e+00,  4.77504438e+01],
       [ 1.03413480e+02,  2.61515748e+01, -2.63244203e+01],
       [ 8.44010434e+01, -2.95250600e+01,  4.39021912e+01],
       [ 1.15477642e+02,  1.30265910e+01, -2.37190009e+01],
       [ 1.35742016e+02, -4.58056353e+01,  5.38323409e+01],
       [ 8.94048835e+01, -6.48361878e+00, -4.30554413e+01],
       [ 1.19329135e+02,  3.34184323e+01, -1.06959776e+01],
       [ 1.07555878e+02, -2.84310958e+01,  2.62586698e+01],
       [ 9.54677867e+01, -1.21651760e+01,  8.30246727e+00]])

In [ ]:
pca.fit_transform(X,Y)

array([[ 14.38798754,  24.0978003 , -48.30606068],
       [-35.32683875,  37.30008903,   7.29706952],
       [ 45.52391782,  -6.82225068, -23.14140684],
       [ 38.77699422,  11.89467327,  16.05715429],
       [  6.18037533,  20.43793519,  11.27944716],
       [-14.63760341,  28.86774735,  23.11120599],
       [  0.47290811, -21.87661846, -16.19431083],
       [ 69.84400861, -26.00976308, -19.21984969],
       [ 39.30277683,  -7.25896752, -21.35094532],
       [ 50.67247016, -26.16755916, -10.20009424],
       [-57.23477761,  -9.71956535, -26.81430381],
       [ 28.75573979,  10.23835503,   5.61025438],
       [  4.06309731, -70.79948899,  14.53686592],
       [ -8.92415683, -21.90799494,  10.69608763],
       [ 37.20697858,  30.11314167,  33.08360057],
       [ -4.99545691,  13.28108046,  17.28424063],
       [ -0.83899929, -48.92179468,  44.95356863],
       [-28.35304725, -36.01122196,  -6.93172186],
       [ 42.52809158, -18.6704863 ,  29.53592181],
       [-25.34961964, -30.98014269,  -2.52054887],
       [ -8.13790323,  32.14627202,   0.74661911],
       [ -9.51920362, -21.3852887 ,  39.64472615],
       [ -2.74008363,  18.91140275,  11.94902994],
       [-15.32845065,  37.07491086,   5.8279938 ],
       [ 13.93158649,  33.82928066, -41.06554163],
       [-17.01085052,  67.50095374,   5.88364446],
       [  6.92755929,  18.68869474, -11.52582572],
       [-14.65206946,   2.42067374, -48.28891172],
       [ 23.03668142, -47.8884506 ,  18.46535721],
       [-14.40057737,  -9.99515127,  -1.99645756],
       [-28.6916565 , -25.23156431,  20.16904842],
       [-33.87605058,  42.86586909,  16.31502976],
       [-30.54467454,  12.74394287,  21.32473309],
       [-19.28350894,  -9.44361739, -17.68108723],
       [ 18.68516907,  -2.50505101, -23.19295008],
       [ -8.82163798,  11.08276627, -42.0127684 ],
       [  9.22288518,  18.89298595,  37.83693214],
       [-34.00291238, -35.1697629 ,  -0.47461387],
       [ 40.32524493,   4.1288854 ,  21.29172234],
       [-26.88661091,   7.3757936 ,   7.74767117],
       [-25.42887338,  -0.87541645, -22.71271649],
       [-43.66505164,  35.84318748,   7.18715734],
       [-34.008549  ,  34.47118398,   4.59973012],
       [ 49.90414179,   7.51818247, -25.25341538],
       [-60.92060831,  29.63168124,  17.47911956],
       [ 10.39615421,  -0.30414888,  -1.18454497],
       [ -5.48951834,  25.62564627,  -7.36164951],
       [ -6.95894973, -58.30366273,  -3.97045794],
       [ 36.33354158,  38.84904857,  -3.37754704],
       [ 18.0684298 ,  -4.92970619,  32.41296251],
       [ 12.59359551,  30.44295752, -45.04184158],
       [ 42.3655001 ,  12.09811854,   9.6511667 ],
       [ 40.71113331,  -6.94357524, -38.39852452],
       [-31.9925248 , -40.14280395, -43.17550518],
       [-10.3258635 , -13.17029446,  17.23226837],
       [ 62.15082042, -17.55820177, -16.00462251],
       [-52.78466288,  32.79644618,   3.61084724],
       [-16.67447198, -57.07117294, -12.11271968],
       [  5.04320915, -21.90645555,   4.90712994],
       [ -5.30419146, -22.54621127,  -1.31666625],
       [ 20.64023886, -57.27061014,   1.26395634],
       [ 12.46571943, -20.60349933,  52.06460645],
       [-14.87323645,  20.16193513,  36.31821704],
       [-40.24288928,   8.35696921, -11.18755459],
       [  3.56390526, -32.00352633,  40.15912933],
       [ -0.96841559,  76.60610948,   5.44466347],
       [-11.59943596,  -9.00605646,  -7.18869353],
       [ 10.02240484,   3.64309612,   5.10770062],
       [-23.28776283,  35.86129678,  18.89201236],
       [ 19.98742862, -39.95383502, -12.09149978],
       [  4.29330902,   5.8733301 , -36.23394872],
       [  8.65792433,  47.0070411 , -25.19395304],
       [ 37.75839254,  32.36756327,  16.05542636],
       [ 53.0109849 ,  31.74585322,  47.10651653],
       [ -7.00919402,   9.68086303, -23.54700123],
       [  3.24206996,  29.79340543, -29.14518009],
       [-35.32172509, -29.09550378, -39.09683433],
       [-42.17606616, -35.22406163, -38.89678245],
       [ 47.98108221,  12.82433098,  46.11490726],
       [-49.23668933, -13.97802041, -20.67865622],
       [ 26.78988764,  36.61772492,  -1.65107894],
       [-10.64662345, -17.04065466,  46.97078464],
       [ 27.53146686,  -7.4952973 ,  13.55758243],
       [ 16.46510127,  -2.4199312 ,  13.37132757],
       [ -1.65852433,  11.94115619,  -2.17314846],
       [-48.87260993,  -7.36650189, -28.2842496 ],
       [  7.55284503,  -8.37999393, -19.68081445],
       [-46.71948365, -31.62952966,  -4.29728559],
       [ -5.79222149, -60.40407218,   7.9093725 ],
       [ 53.40631403, -25.54997862, -24.50772249],
       [  5.12002294,  27.04338576, -37.8779063 ],
       [ -7.33863079, -13.1926972 ,  50.38345118],
       [ 26.68386548,  -2.15754737, -28.63708564],
       [-45.96089213, -21.26490319,  26.78828494],
       [ 19.50959354,   8.35954274, -24.82605683],
       [-39.15253943,   9.24887733,  56.30824709],
       [ -2.67163791,  17.04039922, -45.2969928 ],
       [ 40.63434484,   1.21462463,  10.66945557],
       [-27.68309162,   4.31473919,  32.61300791],
       [-18.40627524,  -6.31934035,  -3.50690103]])